name: frost

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: frontend
    # volumes:
    # working_dir: /workspaces
    # ports:
    #   - "3000:3000"
    command: sleep infinity
    depends_on:
      - backend
    networks:
      - frost-local

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: backend
    # volumes:
    # working_dir: /workspaces
    # ports:
    #   - "3001:3000"
    command: sleep infinity
    depends_on:
      - db
    networks:
      - frost-local

  db:
    # container_name: db
    image: postgres:15
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    # working_dir: /workspaces
    # ports:
    #   - "5432:5432"
    command: sleep infinity
    environment:
      POSTGRES_DB: frost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - frost-local

networks:
  frost-local:
