# +----------------------------------------------------------------------------------------+ #
# |  _____                                          _             _                        | #
# | |  __ \                                        | |           (_)                       | #
# | | |  | |   ___  __   __   ___    ___    _ __   | |_    __ _   _   _ __     ___   _ __  | #
# | | |  | |  / _ \ \ \ / /  / __|  / _ \  | '_ \  | __|  / _` | | | | '_ \   / _ \ | '__| | #
# | | |__| | |  __/  \ V /  | (__  | (_) | | | | | \ |_  | (_| | | | | | | | |  __/ | |    | #
# | |_____/   \___|   \_/    \___|  \___/  |_| |_|  \__|  \__,_| |_| |_| |_|  \___| |_|    | #
# |                                                                                        | #
# +----------------------------------------------------------------------------------------+ #

name: frost-development

services:
  devcontainer:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      target: devcontainer
    volumes:
      - .:/workspaces:cached
    working_dir: /workspaces
    # ports:
    command: sleep infinity
    environment:
      DB_URL: postgresql://postgres:postgres@db:5432/frost
    depends_on:
      - db
    networks:
      - frost-development-local

  db:
    # container_name: db
    image: postgres:16
    restart: always
    volumes:
      - frost-db-data:/var/lib/postgresql/data
    # working_dir: /workspaces
    ports:
      - "5432:5432"
    # command: sleep infinity
    environment:
      POSTGRES_DB: frost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - frost-development-local

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin
    ports:
      - 5678:80
    volumes:
      - frost-pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db
    restart: always
    networks:
      - frost-development-local

volumes:
  frost-db-data:
  frost-pgadmin:

networks:
  frost-development-local:
