# +----------------------------------------------------------------------------------------+ #
# |  _____                                          _             _                        | #
# | |  __ \                                        | |           (_)                       | #
# | | |  | |   ___  __   __   ___    ___    _ __   | |_    __ _   _   _ __     ___   _ __  | #
# | | |  | |  / _ \ \ \ / /  / __|  / _ \  | '_ \  | __|  / _` | | | | '_ \   / _ \ | '__| | #
# | | |__| | |  __/  \ V /  | (__  | (_) | | | | | \ |_  | (_| | | | | | | | |  __/ | |    | #
# | |_____/   \___|   \_/    \___|  \___/  |_| |_|  \__|  \__,_| |_| |_| |_|  \___| |_|    | #
# |                                                                                        | #
# +----------------------------------------------------------------------------------------+ #

name: frost-development

services:
  devcontainer:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      target: devcontainer
    volumes:
      - .:/workspaces:cached
    working_dir: /workspaces
    # ports:
    command: sleep infinity
    networks:
      - frost-development-local

  db:
    # container_name: db
    image: postgres:15
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    # working_dir: /workspaces
    # ports:
    #   - "5432:5432"
    command: sleep infinity
    environment:
      POSTGRES_DB: frost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - frost-development-local

networks:
  frost-development-local:
