openapi: 3.1.0
info:
  version: 0.0.1
  title: Frost API Definition - OpenAPI 3.1
  description: |-
    Frost API Definition

    - [Frost repository](https://github.com/frost-community/frost)
servers:
  - url: https://localhost:3000/api
tags:
  - name: status
    description: status
paths:
  /ping:
    get:
      tags:
        - status
      summary: ping
      description: ""
      operationId: ping
      parameters:
        - name: text
          description: "そのまま返す(optional)"
          schema:
            type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
components:
  schemas:
    Ping:
      type: object
      properties:
        text:
          type: string
          examples: ["hello mrhc!", "hello!"]
