services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: frontend
    working_dir: /workspaces
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - frost-net-internal

  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: server
    working_dir: /workspaces
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    ports:
      - "3001:3001"
    depends_on:
      - server-db
    networks:
      - frost-net-internal

  server-db:
    container_name: server-db
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: server-db
    volumes:
      - ../db/data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d
    command: sleep infinity
    environment:
      POSTGRES_DB: frost_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5432:5432"
    networks:
      - frost-net-internal

  identity-db:
    container_name: identity-db
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: identity-db
    volumes:
      - ../db/data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d
    command: sleep infinity
    environment:
      POSTGRES_DB: frost_identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5432:5432"
    networks:
      - frost-net-internal

networks:
  frost-net-internal:
