services:
  frost:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached

  frost-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    networks:
      - frost-net-backend

  frost-db:
    container_name: frost-db
    image: postgres:15
    restart: unless-stopped
    volumes:
      - frost-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - frost-net-backend

volumes:
  frost-db-data:

networks:
  frost-net-backend:
