openapi: 3.0.0
info:
  title: Frost
  version: 0.1.0
tags: []
paths:
  /api/v1/chatrooms:
    post:
      operationId: ChatRooms_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.ChatRoom'
  /api/v1/chatrooms/{chatRoomId}/members:
    get:
      operationId: ChatRoomMembers_list
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiVersion1.ChatRoomMember'
  /api/v1/chatrooms/{chatRoomId}/members/{userId}:
    post:
      operationId: ChatRoomMembers_create
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.ChatRoomMember'
    delete:
      operationId: ChatRoomMembers_delete
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/chatrooms/{chatRoomId}/posts:
    post:
      operationId: ChatRoomPosts_create
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.Post'
  /api/v1/chatrooms/{chatRoomId}/posts/{postId}:
    get:
      operationId: ChatRoomPosts_get
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.Post'
    delete:
      operationId: ChatRoomPosts_delete
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/chatrooms/{id}:
    delete:
      operationId: ChatRooms_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/me:
    get:
      operationId: Me_get
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.Account'
  /api/v1/timelines/posts:
    post:
      operationId: TimelinePosts_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.Post'
  /api/v1/timelines/posts/{id}:
    get:
      operationId: TimelinePosts_get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.Post'
    delete:
      operationId: TimelinePosts_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/users:
    post:
      operationId: Users_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.User'
  /api/v1/users/{id}:
    get:
      operationId: Users_get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiVersion1.User'
    delete:
      operationId: Users_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
components:
  schemas:
    ApiVersion1.Account:
      type: object
      required:
        - accountId
        - name
        - users
      properties:
        accountId:
          type: string
        name:
          type: string
        users:
          type: array
          items:
            $ref: '#/components/schemas/ApiVersion1.User'
    ApiVersion1.ChatRoom:
      type: object
      required:
        - chatRoomId
      properties:
        chatRoomId:
          type: string
    ApiVersion1.ChatRoomMember:
      type: object
      required:
        - userId
        - chatRoomId
      properties:
        userId:
          type: string
        chatRoomId:
          type: string
    ApiVersion1.Post:
      type: object
      required:
        - postId
      properties:
        postId:
          type: string
    ApiVersion1.User:
      type: object
      required:
        - userId
        - name
        - displayName
      properties:
        userId:
          type: string
        name:
          type: string
        displayName:
          type: string
servers:
  - url: http://localhost:3000
    description: local server
    variables: {}
