openapi: 3.0.0
info:
  title: Frost
  version: 0.1.0
tags: []
paths:
  /api/v1/accounts:
    post:
      operationId: Accounts_registerAccount
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.Account'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.NewAccount'
  /api/v1/chatrooms:
    post:
      operationId: ChatRooms_createChatRoom
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.ChatRoom'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.NewChatRoom'
  /api/v1/chatrooms/{chatRoomId}/members:
    get:
      operationId: ChatRoomMembers_listChatRoomMember
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api.v1.ChatRoomMember'
  /api/v1/chatrooms/{chatRoomId}/members/{userId}:
    post:
      operationId: ChatRoomMembers_createChatRoomMember
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.ChatRoomMember'
    delete:
      operationId: ChatRoomMembers_deleteChatRoomMember
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/chatrooms/{chatRoomId}/posts:
    post:
      operationId: ChatRoomPosts_createChatRoomPost
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.ChatRoomPost'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.NewChatRoomPost'
  /api/v1/chatrooms/{chatRoomId}/posts/{postId}:
    get:
      operationId: ChatRoomPosts_getChatRoomPost
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.ChatRoomPost'
    delete:
      operationId: ChatRoomPosts_deleteChatRoomPost
      parameters:
        - name: chatRoomId
          in: path
          required: true
          schema:
            type: string
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/chatrooms/{id}:
    delete:
      operationId: ChatRooms_deleteChatRoom
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/echo:
    get:
      operationId: Echo_echoGet
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: object
      responses:
        '200':
          description: The request has succeeded.
    post:
      operationId: Echo_echoPost
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /api/v1/me:
    get:
      operationId: Me_getMe
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.Account'
  /api/v1/timelines/posts:
    post:
      operationId: TimelinePosts_createTimelinePost
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.TimelinePost'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.NewTimelinePost'
  /api/v1/timelines/posts/{id}:
    get:
      operationId: TimelinePosts_getTimelinePost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.TimelinePost'
    delete:
      operationId: TimelinePosts_deleteTimelinePost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /api/v1/users:
    post:
      operationId: Users_createUser
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.NewUser'
  /api/v1/users/{id}:
    get:
      operationId: Users_getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.User'
    delete:
      operationId: Users_deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
components:
  schemas:
    Api.v1.Account:
      type: object
      required:
        - accountId
        - name
        - passwordAuthEnabled
        - users
      properties:
        accountId:
          type: string
        name:
          type: string
        passwordAuthEnabled:
          type: boolean
        users:
          type: array
          items:
            $ref: '#/components/schemas/Api.v1.User'
    Api.v1.ChatRoom:
      type: object
      required:
        - chatRoomId
        - title
      properties:
        chatRoomId:
          type: string
        title:
          type: string
    Api.v1.ChatRoomMember:
      type: object
      required:
        - userId
        - chatRoomId
      properties:
        userId:
          type: string
        chatRoomId:
          type: string
    Api.v1.ChatRoomPost:
      type: object
      required:
        - postId
        - chatRoomId
        - userId
        - content
      properties:
        postId:
          type: string
        chatRoomId:
          type: string
        userId:
          type: string
        content:
          type: string
    Api.v1.NewAccount:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string
    Api.v1.NewChatRoom:
      type: object
      required:
        - title
      properties:
        title:
          type: string
    Api.v1.NewChatRoomPost:
      type: object
      required:
        - content
      properties:
        content:
          type: string
    Api.v1.NewTimelinePost:
      type: object
      required:
        - content
      properties:
        content:
          type: string
    Api.v1.NewUser:
      type: object
      required:
        - name
        - displayName
      properties:
        name:
          type: string
        displayName:
          type: string
    Api.v1.TimelinePost:
      type: object
      required:
        - postId
        - userId
        - content
      properties:
        postId:
          type: string
        userId:
          type: string
        content:
          type: string
    Api.v1.User:
      type: object
      required:
        - userId
        - name
        - displayName
      properties:
        userId:
          type: string
        name:
          type: string
        displayName:
          type: string
servers:
  - url: http://localhost:3000
    description: local server
    variables: {}
