openapi: 3.0.0
info:
  title: Frost
  version: 0.1.0
tags:
  - name: Auth
  - name: User
  - name: Leaf
  - name: ChatRoom
paths:
  /api/v1/auth/signin:
    post:
      tags:
        - Auth
        - User
      operationId: AuthApi_Signin
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.AuthInfo'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.SigninBody'
  /api/v1/auth/signup:
    post:
      tags:
        - Auth
        - User
      operationId: AuthApi_Signup
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.AuthInfo'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.SignupBody'
  /api/v1/chatRoom/createChatRoom:
    post:
      tags:
        - ChatRoom
      operationId: ChatRoomApi_CreateChatRoom
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.ChatRoom'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.CreateChatRoomBody'
  /api/v1/chatRoom/createLeaf:
    post:
      tags:
        - ChatRoom
        - Leaf
      operationId: ChatRoomApi_CreateLeaf
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.Leaf'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.CreateChatRoomLeafBody'
  /api/v1/chatRoom/deleteChatRoom:
    post:
      tags:
        - ChatRoom
      operationId: ChatRoomApi_DeleteChatRoom
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.DeleteChatRoomBody'
  /api/v1/chatRoom/getChatRoom:
    get:
      tags:
        - ChatRoom
      operationId: ChatRoomApi_GetChatRoom
      parameters:
        - $ref: '#/components/parameters/Api.v1.GetChatRoomQueryString'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.ChatRoom'
  /api/v1/chatRoom/getTimeline:
    get:
      tags:
        - ChatRoom
        - Leaf
      operationId: ChatRoomApi_GetTimeline
      parameters:
        - $ref: '#/components/parameters/Api.v1.GetChatRoomTimelineQueryString.nextCursor'
        - $ref: '#/components/parameters/Api.v1.GetChatRoomTimelineQueryString.prevCursor'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api.v1.Leaf'
  /api/v1/chatRoom/searchChatRooms:
    get:
      tags:
        - ChatRoom
      operationId: ChatRoomApi_SearchChatRooms
      parameters:
        - $ref: '#/components/parameters/Api.v1.SearchChatRoomsQueryString.nextCursor'
        - $ref: '#/components/parameters/Api.v1.SearchChatRoomsQueryString.prevCursor'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api.v1.ChatRoom'
  /api/v1/echo:
    get:
      operationId: RootApi_GetEcho
      parameters:
        - name: message
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
    post:
      operationId: RootApi_PostEcho
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
  /api/v1/leaf/createLeaf:
    post:
      tags:
        - Leaf
      operationId: LeafApi_CreateLeaf
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.Leaf'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.CreateLeafBody'
  /api/v1/leaf/deleteLeaf:
    post:
      tags:
        - Leaf
      operationId: LeafApi_DeleteLeaf
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.DeleteLeafBody'
  /api/v1/leaf/getLeaf:
    get:
      tags:
        - Leaf
      operationId: LeafApi_GetLeaf
      parameters:
        - $ref: '#/components/parameters/Api.v1.GetLeafQueryString'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.Leaf'
  /api/v1/leaf/searchLeafs:
    get:
      tags:
        - Leaf
      operationId: LeafApi_SearchLeafs
      parameters:
        - $ref: '#/components/parameters/Api.v1.SearchLeafsQueryString.nextCursor'
        - $ref: '#/components/parameters/Api.v1.SearchLeafsQueryString.prevCursor'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api.v1.Leaf'
  /api/v1/user/deleteUser:
    post:
      tags:
        - User
      operationId: UserApi_DeleteUser
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.DeleteUserBody'
  /api/v1/user/followUser:
    post:
      tags:
        - User
      operationId: UserApi_FollowUser
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.FollowUserBody'
  /api/v1/user/getFollowings:
    get:
      tags:
        - User
      operationId: UserApi_GetFollowings
      parameters:
        - $ref: '#/components/parameters/Api.v1.GetFollowingsQueryString.userId'
        - $ref: '#/components/parameters/Api.v1.GetFollowingsQueryString.nextCursor'
        - $ref: '#/components/parameters/Api.v1.GetFollowingsQueryString.prevCursor'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api.v1.User'
  /api/v1/user/getHomeTimeline:
    get:
      tags:
        - User
        - Leaf
      operationId: UserApi_GetHomeTimeline
      parameters:
        - $ref: '#/components/parameters/Api.v1.GetHomeTimelineQueryString.nextCursor'
        - $ref: '#/components/parameters/Api.v1.GetHomeTimelineQueryString.prevCursor'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api.v1.Leaf'
  /api/v1/user/getUser:
    get:
      tags:
        - User
      operationId: UserApi_GetUser
      parameters:
        - $ref: '#/components/parameters/Api.v1.GetUserQueryString.userId'
        - $ref: '#/components/parameters/Api.v1.GetUserQueryString.username'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api.v1.User'
  /api/v1/user/searchUsers:
    get:
      tags:
        - User
      operationId: UserApi_SearchUsers
      parameters:
        - $ref: '#/components/parameters/Api.v1.SearchUsersQueryString.nextCursor'
        - $ref: '#/components/parameters/Api.v1.SearchUsersQueryString.prevCursor'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api.v1.User'
  /api/v1/user/unfollowUser:
    post:
      tags:
        - User
      operationId: UserApi_UnfollowUser
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api.v1.UnfollowUserBody'
components:
  parameters:
    Api.v1.GetChatRoomQueryString:
      name: chatRoomId
      in: query
      required: true
      schema:
        type: string
    Api.v1.GetChatRoomTimelineQueryString.nextCursor:
      name: nextCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.GetChatRoomTimelineQueryString.prevCursor:
      name: prevCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.GetFollowingsQueryString.nextCursor:
      name: nextCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.GetFollowingsQueryString.prevCursor:
      name: prevCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.GetFollowingsQueryString.userId:
      name: userId
      in: query
      required: true
      schema:
        type: string
    Api.v1.GetHomeTimelineQueryString.nextCursor:
      name: nextCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.GetHomeTimelineQueryString.prevCursor:
      name: prevCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.GetLeafQueryString:
      name: leafId
      in: query
      required: true
      schema:
        type: string
    Api.v1.GetUserQueryString.userId:
      name: userId
      in: query
      required: false
      schema:
        type: string
    Api.v1.GetUserQueryString.username:
      name: username
      in: query
      required: false
      schema:
        type: string
    Api.v1.SearchChatRoomsQueryString.nextCursor:
      name: nextCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.SearchChatRoomsQueryString.prevCursor:
      name: prevCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.SearchLeafsQueryString.nextCursor:
      name: nextCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.SearchLeafsQueryString.prevCursor:
      name: prevCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.SearchUsersQueryString.nextCursor:
      name: nextCursor
      in: query
      required: false
      schema:
        type: string
    Api.v1.SearchUsersQueryString.prevCursor:
      name: prevCursor
      in: query
      required: false
      schema:
        type: string
  schemas:
    Api.v1.AuthInfo:
      type: object
      required:
        - accessToken
        - refreshToken
        - user
      properties:
        accessToken:
          $ref: '#/components/schemas/Api.v1.Token'
        refreshToken:
          $ref: '#/components/schemas/Api.v1.Token'
        user:
          $ref: '#/components/schemas/Api.v1.User'
    Api.v1.ChatRoom:
      type: object
      required:
        - chatRoomId
        - title
        - description
      properties:
        chatRoomId:
          type: string
        title:
          type: string
        description:
          type: string
    Api.v1.CreateChatRoomBody:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
    Api.v1.CreateChatRoomLeafBody:
      type: object
      required:
        - chatRoomId
        - content
      properties:
        chatRoomId:
          type: string
        content:
          type: string
    Api.v1.CreateLeafBody:
      type: object
      required:
        - content
      properties:
        content:
          type: string
    Api.v1.DeleteChatRoomBody:
      type: object
      required:
        - chatRoomId
      properties:
        chatRoomId:
          type: string
    Api.v1.DeleteLeafBody:
      type: object
      required:
        - leafId
      properties:
        leafId:
          type: string
    Api.v1.DeleteUserBody:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
    Api.v1.FollowUserBody:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
    Api.v1.Leaf:
      type: object
      required:
        - leafId
        - userId
        - content
      properties:
        leafId:
          type: string
        chatRoomId:
          type: string
        userId:
          type: string
        content:
          type: string
    Api.v1.SigninBody:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        password:
          type: string
    Api.v1.SignupBody:
      type: object
      required:
        - name
        - displayName
      properties:
        name:
          type: string
        password:
          type: string
        displayName:
          type: string
    Api.v1.Token:
      type: object
      required:
        - token
        - scopes
      properties:
        token:
          type: string
        scopes:
          type: array
          items:
            type: string
    Api.v1.UnfollowUserBody:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
    Api.v1.User:
      type: object
      required:
        - userId
        - name
        - displayName
        - passwordAuthEnabled
      properties:
        userId:
          type: string
        name:
          type: string
        displayName:
          type: string
        passwordAuthEnabled:
          type: boolean
servers:
  - url: http://localhost:3000
    description: local server
    variables: {}
