name: ESLint CI

on:
  push:
    paths:
      - "frontend/src/**"
      - ".github/workflows/front-lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "latest"
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm lint
