name: ESLint CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/front-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - run: cd frontend
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "latest"
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm lint
